package org.springframework.social.twitter.api.advertising;

public enum TargetingType {
    AGE,
    FOLLOWERS_OF_USER,
    SIMILAR_TO_FOLLOWERS_OF_USER,
    INTEREST,
    LOCATION,
    PLATFORM,
    PLATFORM_VERSION,
    DEVICE,
    WIFI_ONLY,
    GENDER,
    TV_CHANNEL,
    TV_GENRE,
    TV_SHOW,
    TV_SHOW_AIRING_RESTRICTED,

    NETWORK_OPERATOR,
    NETWORK_ACTIVATION_DURATION_LT,
    NETWORK_ACTIVATION_DURATION_GTE,

    BROAD_KEYWORD,
    UNORDERED_KEYWORD,
    PHRASE_KEYWORD,
    EXACT_KEYWORD,
    NEGATIVE_PHRASE_KEYWORD,
    NEGATIVE_UNORDERED_KEYWORD,
    NEGATIVE_EXACT_KEYWORD,

    TAILORED_AUDIENCE,

    BEHAVIOR,
    NEGATIVE_BEHAVIOR,
    BEHAVIOR_EXPANDED,

    APP_STORE_CATEGORY,
    APP_STORE_CATEGORY_LOOKALIKE,
    EXCLUDE_APP_LIST
}
